version: '3'

services:
  mongo:
    image: 'mongo:3.6'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
  api:
    build: 
      context: .
    restart: always
    depends_on:
      - 'mongo'
    volumes:
      - .:/code
    ports:
      - 4567:4567
    environment:
      # MONGODB_URL: mongodb://mongo:27017/wernextgen-qa
      MONGODB_URL: mongodb://qa-db-user-1:wrngpassword1@ds241895.mlab.com:41895/wernextgen-qa
  web:
    build:
      context: ../we-r-next-generation-web
    restart: always
    depends_on:
      - 'api'
    volumes:
      - ../we-r-next-generation-web:/code
    ports:
      - 8080:8080